const teamNames={ARI:'Arizona',ATL:'Atlanta',BAL:'Baltimore',BUF:'Buffalo',CAR:'Carolina',CHI:'Chicago',CIN:'Cincinnati',CLE:'Cleveland',DAL:'Dallas',DEN:'Denver',DET:'Detroit',GB:'Green Bay',HOU:'Houston',IND:'Indianapolis',JAX:'Jacksonville',KC:'Kansas City',LV:'Las Vegas',LAC:'LA Chargers',LAR:'LA Rams',MIA:'Miami',MIN:'Minnesota',NE:'New England',NO:'New Orleans',NYG:'NY Giants',NYJ:'NY Jets',PHI:'Philadelphia',PIT:'Pittsburgh',SEA:'Seattle',SF:'San Francisco',TB:'Tampa Bay',TEN:'Tennessee',WAS:'Washington'};
const fmt=p=>`${Math.round(Number(p)*100)} %`;
function renderForecasts(data){const games=Array.isArray(data.forecasts)?data.forecasts:[];if(!games.length)return;document.querySelector('#forecastCount').textContent=games.length;document.querySelector('#statusLabel').textContent='PÄIVITETTY';document.querySelector('#updatedAt').textContent=`Lukittu ${new Date(data.cutoff).toLocaleString('fi-FI',{dateStyle:'medium',timeStyle:'short'})} · Malli ${data.model_version}`;document.querySelector('#forecastGrid').innerHTML=games.map(g=>{const hp=Number(g.home_win_probability);return `<article class="game-card"><div class="team"><span>VIERAS</span><strong>${teamNames[g.away_team]||g.away_team}</strong></div><div><div class="probbar"><i style="width:${(1-hp)*100}%"></i></div><div class="prob-labels"><b>${fmt(1-hp)}</b><b>${fmt(hp)}</b></div></div><div class="team"><span>KOTI</span><strong>${teamNames[g.home_team]||g.home_team}</strong></div></article>`}).join('')}
fetch('./public/data/latest.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(renderForecasts).catch(()=>{});

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function renderStatus(data){const node=document.querySelector('#operationsStatus');if(!node)return;const fetched=data.data_fetched_at?new Date(data.data_fetched_at).toLocaleString('fi-FI',{dateStyle:'medium',timeStyle:'short'}):'ei vielä tuotantoajoa';const week=data.source_week??'—';const warnings=Array.isArray(data.warnings)?data.warnings.length:0;node.textContent=`Data haettu: ${fetched} · lähdeviikko ${week} · ledger-rivejä ${data.ledger_entries??0} · varoituksia ${warnings}`;}
fetch('./public/data/status.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(renderStatus).catch(()=>{});

function renderMovers(rows){const panel=document.querySelector('#moversPanel');if(!panel||!Array.isArray(rows)||!rows.length)return;panel.hidden=false;document.querySelector('#moversList').innerHTML=rows.map(row=>`<article class="content-card"><span class="meta">${esc(row.game_id)}</span><h2>${Number(row.move)>=0?'+':''}${(Number(row.move)*100).toFixed(1)} %-yks.</h2><p>${esc(row.move_reason)}</p><span class="arrow">${fmt(row.home_win_probability)}</span></article>`).join('');}
fetch('./public/data/movers.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(renderMovers).catch(()=>{});

function renderReview(data){const panel=document.querySelector('#reviewPanel');if(!panel)return;panel.hidden=false;const games=Array.isArray(data.games)?data.games:[];document.querySelector('#reviewGames').innerHTML=games.map(game=>`<article class="review-game"><strong>${esc(game.away_team)} @ ${esc(game.home_team)}</strong><span>${esc(game.away_qb_id)} / ${esc(game.home_qb_id)}</span><span>${fmt(game.home_win_probability)} koti</span></article>`).join('')||'<p>Ei valmisteltua ottelulistaa.</p>';const issues=[...(data.errors||[]),...(data.warnings||[])];document.querySelector('#reviewIssues').innerHTML=issues.map(item=>`<li>${esc(item)}</li>`).join('')||'<li>Kaikki julkaisuportit kunnossa.</li>';}
fetch('./public/data/review.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(renderReview).catch(()=>{});

function renderPerformance(data){if(!document.querySelector('#brierMetric'))return;document.querySelector('#brierMetric').textContent=Number(data.model.brier).toFixed(3);document.querySelector('#logLossMetric').textContent=Number(data.model.log_loss).toFixed(3);document.querySelector('#rollingMetric').textContent=Number(data.rolling.brier).toFixed(3);document.querySelector('#scoredGames').textContent=data.model.games;}
fetch('./public/data/performance.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(renderPerformance).catch(()=>{});
